### ISSUE TITLE
Pre-Launch Todo

### ISSUE THREAD

**Issue by drurez** [drurez/portfolio#2]
- [ ] Add Footer content
- [ ] Add copy to Education section on Resume
- [ ] Fix mobile typography and spacing
- [ ] create favicon icon
- [ ] Add more images to Miscellaneous page
- [ ] Fix gallery size of Misc page on mobile
- [ ] Replace any lorem ipsum content with real content
- [ ] Re-organize REI page
- [ ] Add Contact Information
- [ ] Add Hamburger Menu
